package austalumniassociationnb;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestedapplytable_btn = new javax.swing.JButton();
        mainalumnitable_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        evbtn = new javax.swing.JButton();
        upcominhEventbtn = new javax.swing.JButton();
        prevevbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        requestedapplytable_btn.setBackground(new java.awt.Color(0, 204, 255));
        requestedapplytable_btn.setFont(new java.awt.Font("Berlin Sans FB", 3, 14)); // NOI18N
        requestedapplytable_btn.setForeground(new java.awt.Color(255, 0, 0));
        requestedapplytable_btn.setText("Requested Apply Table");
        requestedapplytable_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestedapplytable_btnActionPerformed(evt);
            }
        });

        mainalumnitable_btn.setBackground(new java.awt.Color(0, 204, 255));
        mainalumnitable_btn.setFont(new java.awt.Font("Berlin Sans FB", 3, 14)); // NOI18N
        mainalumnitable_btn.setForeground(new java.awt.Color(255, 0, 0));
        mainalumnitable_btn.setText("Main Alumni Table");
        mainalumnitable_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainalumnitable_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainalumnitable_btnActionPerformed(evt);
            }
        });

        back_btn.setBackground(new java.awt.Color(0, 204, 255));
        back_btn.setFont(new java.awt.Font("Berlin Sans FB", 3, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 0, 0));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        evbtn.setBackground(new java.awt.Color(0, 204, 255));
        evbtn.setFont(new java.awt.Font("Berlin Sans FB", 3, 14)); // NOI18N
        evbtn.setForeground(new java.awt.Color(255, 0, 0));
        evbtn.setText("Event Form");
        evbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evbtnActionPerformed(evt);
            }
        });

        upcominhEventbtn.setBackground(new java.awt.Color(0, 204, 255));
        upcominhEventbtn.setFont(new java.awt.Font("Berlin Sans FB", 3, 14)); // NOI18N
        upcominhEventbtn.setForeground(new java.awt.Color(255, 0, 0));
        upcominhEventbtn.setText("Upcoming Events");
        upcominhEventbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upcominhEventbtnActionPerformed(evt);
            }
        });

        prevevbtn.setBackground(new java.awt.Color(0, 204, 255));
        prevevbtn.setFont(new java.awt.Font("Berlin Sans FB", 3, 14)); // NOI18N
        prevevbtn.setForeground(new java.awt.Color(255, 0, 0));
        prevevbtn.setText("All Previous Events Details");
        prevevbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevevbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(requestedapplytable_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainalumnitable_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(evbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prevevbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upcominhEventbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(requestedapplytable_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainalumnitable_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(evbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(upcominhEventbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prevevbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainalumnitable_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainalumnitable_btnActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainalumnitable_btnActionPerformed

    private void requestedapplytable_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestedapplytable_btnActionPerformed
        // TODO add your handling code here:
        new RequestedApplyTable().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_requestedapplytable_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
         new SignIn().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void evbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evbtnActionPerformed
        // TODO add your handling code here:
        new EventFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_evbtnActionPerformed

    private void upcominhEventbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upcominhEventbtnActionPerformed
        // TODO add your handling code here:
         new UpevAdmin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_upcominhEventbtnActionPerformed

    private void prevevbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevevbtnActionPerformed
        // TODO add your handling code here:
         new AllPrevEv().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_prevevbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton evbtn;
    private javax.swing.JButton mainalumnitable_btn;
    private javax.swing.JButton prevevbtn;
    private javax.swing.JButton requestedapplytable_btn;
    private javax.swing.JButton upcominhEventbtn;
    // End of variables declaration//GEN-END:variables
}
